Carrinho
lmtsufape/ecommerce-gestao-agricola-api pull request #39
Opened 2023-03-15 19:46 UTC by IvandoNascimento

2023-03-21 01:47 UTC, ThiagoCavalcantiSilva requested changes

2023-03-21 01:47 UTC, ThiagoCavalcantiSilva commented on app/Http/Controllers/Api/SacolaController.php
> +            return response()->json(['erro' =>'O carrinho está vazio'],400);
Código de erro não é o adequado. Talvez 404 faça mais sentido pra esse contexto

2023-03-21 01:47 UTC, ThiagoCavalcantiSilva commented on app/Http/Controllers/Api/SacolaController.php
> +		->select(DB::raw("produtos.preco as produto_preço"), "nome",DB::raw("item_sacolas.preco as preço"),
Retirar caracteres especiais. Pode deixar 'preco' mesmo

2023-03-21 01:47 UTC, ThiagoCavalcantiSilva commented on app/Http/Controllers/Api/SacolaController.php
> +            $item->update(['preço'=>$item->preco+$valorCompra,'quantidade'=>$item->quantidade+$request->quantidade]);
Mesmo caso anterior, pode remover o cedilha sem problemas

2023-03-21 02:33 UTC, IvandoNascimento commented on database/migrations/2023_03_02_024431_create_sacolas_table.php
> +            $table->foreignId('loja_id')->nullable(false)->constrained('bancas');
Seria mais simples, mas fiz seguindo o mer. Dá pra fazer a relação atráves do model, usando o Through do eloquent, eu acho.

2023-03-21 02:34 UTC, IvandoNascimento commented on app/Http/Controllers/Api/SacolaController.php
> +        ->join("produtos","produtos.id","=","produto_id")
Não faz diferença em questão de resultado, o query builder do laravel faz essa mágica, como não tem colunas iguais, não precisa citar explicitamente a tabela, mas posso colocar, para o código ficar mais limpo.

2023-03-21 02:34 UTC, IvandoNascimento commented on app/Http/Controllers/Api/SacolaController.php
> +    public function store(Request $request)
Usei o padrão do laravel de actions do controller, acho que não precisa mudar

2023-03-21 02:38 UTC, IvandoNascimento commented on app/Http/Controllers/Api/SacolaController.php
> +		->select(DB::raw("produtos.preco as produto_preço"), "nome",DB::raw("item_sacolas.preco as preço"),
Ele pega o nome do produto mesmo

2023-03-21 11:38 UTC, luiz-davi commented on database/migrations/2023_03_02_024431_create_sacolas_table.php
> +            $table->foreignId('loja_id')->nullable(false)->constrained('bancas');
O mer não está pronto, está sujeito a mudanças. Se tu achar algo inconsistente, só mudar no código, e depois no mer.

2023-03-21 11:39 UTC, luiz-davi commented on database/migrations/2023_03_02_024431_create_sacolas_table.php
> +            $table->foreignId('loja_id')->nullable(false)->constrained('bancas');
O mer não está pronto, está sujeito a mudanças. Se tu achar algo inconsistente, só mudar no código, e depois no mer.

2023-03-22 00:49 UTC, ThiagoCavalcantiSilva approved these changes

2023-03-22 22:41 UTC, luiz-davi approved these changes

2023-03-23 00:45 UTC, merged